### ISSUE TITLE
Exercise22a.c (Triangle Problem)

### ISSUE THREAD

**Issue by Uzayky** [Uzayky/W3Resources-Solutions#4]
![screenshot from 2017-10-08 22-53-15](https://user-images.githubusercontent.com/32466970/31320331-81d7b21a-ac7b-11e7-8475-30e5a7434c02.png)

**Her değer için üçgen olabilecegini söylüyor ama if kısmına uymuyor(Else kısmına hiç girmiyor).**

**Code creates a triangle for all ''invalid'' inputs; if/else parts of code doesn't work correctly.**

**Comment by cagataycali** [comment]
https://github.com/Uzayky/W3Resources-Solutions/blob/master/Basic%20Declarations%20and%20Expressions/Exercise22a.c#L28 bu şekilde 3'lü sıralama yapamazsın :)

**Comment by Uzayky** [comment]
Sağol
